name: neext
dependencies:
  - python==3.12.13
  - numpy==1.26.4
  - pandas==2.3.3
  - jupyter==1.1.1
  - matplotlib==3.10.8
  - scikit-learn==1.4.2
  - pycairo==1.29.0
  - pip==26.0.1
  - seaborn==0.13.2
  - pip:
    - igraph==1.0.0
    - umap-learn==0.5.7
    - partition-igraph==0.0.8
    - neext==0.2.11
    